/* Copyright (c) 2002-2012 Croteam Ltd. 
This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation


This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. */

#pragma warning(disable: 4305)

wpn_fH[WEAPON_NONE] = (FLOAT)0;
wpn_fP[WEAPON_NONE] = (FLOAT)0;
wpn_fB[WEAPON_NONE] = (FLOAT)0;
wpn_fX[WEAPON_NONE] = (FLOAT)0;
wpn_fY[WEAPON_NONE] = (FLOAT)0;
wpn_fZ[WEAPON_NONE] = (FLOAT)0;
wpn_fFOV[WEAPON_NONE] = (FLOAT)0;
wpn_fClip[WEAPON_NONE] = (FLOAT)0;
wpn_fFX[WEAPON_NONE] = (FLOAT)0;
wpn_fFY[WEAPON_NONE] = (FLOAT)0;

wpn_fH[WEAPON_KNIFE] = (FLOAT)-1;
wpn_fP[WEAPON_KNIFE] = (FLOAT)10;
wpn_fB[WEAPON_KNIFE] = (FLOAT)6;
wpn_fX[WEAPON_KNIFE] = (FLOAT)0.23;
wpn_fY[WEAPON_KNIFE] = (FLOAT)-0.28;
wpn_fZ[WEAPON_KNIFE] = (FLOAT)-0.44;
wpn_fFOV[WEAPON_KNIFE] = (FLOAT)41.5;
wpn_fClip[WEAPON_KNIFE] = (FLOAT)0.1;
wpn_fFX[WEAPON_KNIFE] = (FLOAT)0;
wpn_fFY[WEAPON_KNIFE] = (FLOAT)0;

wpn_fH[WEAPON_COLT] = (FLOAT)-1;
wpn_fP[WEAPON_COLT] = (FLOAT)0;
wpn_fB[WEAPON_COLT] = (FLOAT)0;
wpn_fX[WEAPON_COLT] = (FLOAT)0.19;
wpn_fY[WEAPON_COLT] = (FLOAT)-0.21;
wpn_fZ[WEAPON_COLT] = (FLOAT)-0.1;
wpn_fFOV[WEAPON_COLT] = (FLOAT)57;
wpn_fClip[WEAPON_COLT] = (FLOAT)0.1;
wpn_fFX[WEAPON_COLT] = (FLOAT)0;
wpn_fFY[WEAPON_COLT] = (FLOAT)0;

wpn_fH[WEAPON_DOUBLECOLT] = (FLOAT)-1;
wpn_fP[WEAPON_DOUBLECOLT] = (FLOAT)0;
wpn_fB[WEAPON_DOUBLECOLT] = (FLOAT)0;
wpn_fX[WEAPON_DOUBLECOLT] = (FLOAT)0.19;
wpn_fY[WEAPON_DOUBLECOLT] = (FLOAT)-0.21;
wpn_fZ[WEAPON_DOUBLECOLT] = (FLOAT)-0.1;
wpn_fFOV[WEAPON_DOUBLECOLT] = (FLOAT)57;
wpn_fClip[WEAPON_DOUBLECOLT] = (FLOAT)0.1;
wpn_fFX[WEAPON_DOUBLECOLT] = (FLOAT)0;
wpn_fFY[WEAPON_DOUBLECOLT] = (FLOAT)0;

wpn_fH[WEAPON_SINGLESHOTGUN] = (FLOAT)2;
wpn_fP[WEAPON_SINGLESHOTGUN] = (FLOAT)2;
wpn_fB[WEAPON_SINGLESHOTGUN] = (FLOAT)0;
wpn_fX[WEAPON_SINGLESHOTGUN] = (FLOAT)0.12;
wpn_fY[WEAPON_SINGLESHOTGUN] = (FLOAT)-0.22;
wpn_fZ[WEAPON_SINGLESHOTGUN] = (FLOAT)-0.34;
wpn_fFOV[WEAPON_SINGLESHOTGUN] = (FLOAT)41;
wpn_fClip[WEAPON_SINGLESHOTGUN] = (FLOAT)0.1;
wpn_fFX[WEAPON_SINGLESHOTGUN] = (FLOAT)0;
wpn_fFY[WEAPON_SINGLESHOTGUN] = (FLOAT)0;

wpn_fH[WEAPON_DOUBLESHOTGUN] = (FLOAT)2;
wpn_fP[WEAPON_DOUBLESHOTGUN] = (FLOAT)1;
wpn_fB[WEAPON_DOUBLESHOTGUN] = (FLOAT)0;
wpn_fX[WEAPON_DOUBLESHOTGUN] = (FLOAT)0.13;
wpn_fY[WEAPON_DOUBLESHOTGUN] = (FLOAT)-0.21;
wpn_fZ[WEAPON_DOUBLESHOTGUN] = (FLOAT)-0.364;
wpn_fFOV[WEAPON_DOUBLESHOTGUN] = (FLOAT)52.5;
wpn_fClip[WEAPON_DOUBLESHOTGUN] = (FLOAT)0.1;
wpn_fFX[WEAPON_DOUBLESHOTGUN] = (FLOAT)0;
wpn_fFY[WEAPON_DOUBLESHOTGUN] = (FLOAT)0;

wpn_fH[WEAPON_TOMMYGUN] = (FLOAT)4;
wpn_fP[WEAPON_TOMMYGUN] = (FLOAT)3;
wpn_fB[WEAPON_TOMMYGUN] = (FLOAT)0;
wpn_fX[WEAPON_TOMMYGUN] = (FLOAT)0.121;
wpn_fY[WEAPON_TOMMYGUN] = (FLOAT)-0.213;
wpn_fZ[WEAPON_TOMMYGUN] = (FLOAT)-0.285;
wpn_fFOV[WEAPON_TOMMYGUN] = (FLOAT)49;
wpn_fClip[WEAPON_TOMMYGUN] = (FLOAT)0.1;
wpn_fFX[WEAPON_TOMMYGUN] = (FLOAT)0;
wpn_fFY[WEAPON_TOMMYGUN] = (FLOAT)0;

wpn_fH[WEAPON_MINIGUN] = (FLOAT)2;
wpn_fP[WEAPON_MINIGUN] = (FLOAT)0;
wpn_fB[WEAPON_MINIGUN] = (FLOAT)0;
wpn_fX[WEAPON_MINIGUN] = (FLOAT)0.137;
wpn_fY[WEAPON_MINIGUN] = (FLOAT)-0.24;
wpn_fZ[WEAPON_MINIGUN] = (FLOAT)-0.328;
wpn_fFOV[WEAPON_MINIGUN] = (FLOAT)66.9;
wpn_fClip[WEAPON_MINIGUN] = (FLOAT)0.1;
wpn_fFX[WEAPON_MINIGUN] = (FLOAT)0;
wpn_fFY[WEAPON_MINIGUN] = (FLOAT)0;

wpn_fH[WEAPON_ROCKETLAUNCHER] = (FLOAT)2;
wpn_fP[WEAPON_ROCKETLAUNCHER] = (FLOAT)1;
wpn_fB[WEAPON_ROCKETLAUNCHER] = (FLOAT)0;
wpn_fX[WEAPON_ROCKETLAUNCHER] = (FLOAT)0.17;
wpn_fY[WEAPON_ROCKETLAUNCHER] = (FLOAT)-0.325;
wpn_fZ[WEAPON_ROCKETLAUNCHER] = (FLOAT)-0.24;
wpn_fFOV[WEAPON_ROCKETLAUNCHER] = (FLOAT)66;
wpn_fClip[WEAPON_ROCKETLAUNCHER] = (FLOAT)0.1;
wpn_fFX[WEAPON_ROCKETLAUNCHER] = (FLOAT)-0.1;
wpn_fFY[WEAPON_ROCKETLAUNCHER] = (FLOAT)0.11;

wpn_fH[WEAPON_GRENADELAUNCHER] = (FLOAT)2;
wpn_fP[WEAPON_GRENADELAUNCHER] = (FLOAT)6;
wpn_fB[WEAPON_GRENADELAUNCHER] = (FLOAT)0;
wpn_fX[WEAPON_GRENADELAUNCHER] = (FLOAT)0.14;
wpn_fY[WEAPON_GRENADELAUNCHER] = (FLOAT)-0.41;
wpn_fZ[WEAPON_GRENADELAUNCHER] = (FLOAT)-0.335001;
wpn_fFOV[WEAPON_GRENADELAUNCHER] = (FLOAT)44.5;
wpn_fClip[WEAPON_GRENADELAUNCHER] = (FLOAT)0.1;
wpn_fFX[WEAPON_GRENADELAUNCHER] = (FLOAT)0;
wpn_fFY[WEAPON_GRENADELAUNCHER] = (FLOAT)0;

wpn_fH[WEAPON_LASER] = (FLOAT)1;
wpn_fP[WEAPON_LASER] = (FLOAT)3;
wpn_fB[WEAPON_LASER] = (FLOAT)0;
wpn_fX[WEAPON_LASER] = (FLOAT)0.141;
wpn_fY[WEAPON_LASER] = (FLOAT)-0.174;
wpn_fZ[WEAPON_LASER] = (FLOAT)-0.175;
wpn_fFOV[WEAPON_LASER] = (FLOAT)70.5;
wpn_fClip[WEAPON_LASER] = (FLOAT)0.1;
wpn_fFX[WEAPON_LASER] = (FLOAT)-0.1;
wpn_fFY[WEAPON_LASER] = (FLOAT)-0.4;

wpn_fH[WEAPON_IRONCANNON] = (FLOAT)2.5;
wpn_fP[WEAPON_IRONCANNON] = (FLOAT)6;
wpn_fB[WEAPON_IRONCANNON] = (FLOAT)0;
wpn_fX[WEAPON_IRONCANNON] = (FLOAT)0.225;
wpn_fY[WEAPON_IRONCANNON] = (FLOAT)-0.345;
wpn_fZ[WEAPON_IRONCANNON] = (FLOAT)-0.57;
wpn_fFOV[WEAPON_IRONCANNON] = (FLOAT)57;
wpn_fClip[WEAPON_IRONCANNON] = (FLOAT)0.1;
wpn_fFX[WEAPON_IRONCANNON] = (FLOAT)0.25;
wpn_fFY[WEAPON_IRONCANNON] = (FLOAT)-0.5;

wpn_fH[WEAPON_LAST] = (FLOAT)0;
wpn_fP[WEAPON_LAST] = (FLOAT)0;
wpn_fB[WEAPON_LAST] = (FLOAT)0;
wpn_fX[WEAPON_LAST] = (FLOAT)0;
wpn_fY[WEAPON_LAST] = (FLOAT)0;
wpn_fZ[WEAPON_LAST] = (FLOAT)0;
wpn_fFOV[WEAPON_LAST] = (FLOAT)0;
wpn_fClip[WEAPON_LAST] = (FLOAT)0;
wpn_fFX[WEAPON_LAST] = (FLOAT)0;
wpn_fFY[WEAPON_LAST] = (FLOAT)0;

/*
_pShell->DeclareSymbol("user FLOAT wpn_fH[30+1];",    &wpn_fH);
_pShell->DeclareSymbol("user FLOAT wpn_fP[30+1];",    &wpn_fP);
_pShell->DeclareSymbol("user FLOAT wpn_fB[30+1];",    &wpn_fB);
_pShell->DeclareSymbol("user FLOAT wpn_fX[30+1];",    &wpn_fX);
_pShell->DeclareSymbol("user FLOAT wpn_fY[30+1];",    &wpn_fY);
_pShell->DeclareSymbol("user FLOAT wpn_fZ[30+1];",    &wpn_fZ);
_pShell->DeclareSymbol("user FLOAT wpn_fFOV[30+1];",  &wpn_fFOV);
_pShell->DeclareSymbol("user FLOAT wpn_fClip[30+1];", &wpn_fClip);
_pShell->DeclareSymbol("user FLOAT wpn_fFX[30+1];",   &wpn_fFX);
_pShell->DeclareSymbol("user FLOAT wpn_fFY[30+1];",   &wpn_fFY);
*/

#pragma warning(default: 4305)
